import { createSession, score, validSession } from './quiz.js';
const main = document.querySelector('main');
const KEY = 'medborgarskapsprov-v1';
let questions = [], lang = 'sv', session = null, history = [], view = 'home', deferredInstall;
let storageOK = true;
const t = (sv, en) => lang === 'sv' ? sv : en;
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save() { try { localStorage.setItem(KEY, JSON.stringify({lang, session, history})); } catch { storageOK = false; } }
function source(q) { return `<a class="source-link" href="./reader.html?question=${q.id}&lang=${lang}" target="_blank" rel="noopener">Sverige i fokus · ${t('sida','page')} ${q.page} <span aria-hidden="true">↗</span></a>`; }
function validationStatus(q) { return `<p class="validation-status ${q.validated === true ? 'validated' : 'unvalidated'}">${q.validated === true ? t('Validerad av en människa','Validated by a human') : t('Ännu inte validerad av en människa','Not yet validated by a human')}</p>`; }
function excerpts(q) { return `<div class="source-heading"><span>${t('LÄS & FÖRSTÅ','READ & UNDERSTAND')}</span>${source(q)}</div><div class="excerpts"><div lang="sv"><span class="eyebrow">SVENSKA · ${t('ORIGINALTEXT','ORIGINAL TEXT')}</span><blockquote>${esc(q.excerpt.sv)}</blockquote></div><div lang="en"><span class="eyebrow">ENGLISH · ${t('ÖVERSÄTTNING','TRANSLATION')}</span><blockquote>${esc(q.excerpt.en)}</blockquote></div></div>`; }
function languageUI() {
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-lang]').forEach(b => { b.classList.toggle('active', b.dataset.lang === lang); b.setAttribute('aria-pressed', String(b.dataset.lang === lang)); });
  document.querySelector('#footer-note').textContent = t('Fristående övningsapp · Baserad på Sverige i fokus, 2026','Independent practice app · Based on Sverige i fokus, 2026');
  document.querySelector('#install').textContent = t('Installera app','Install app');
  document.querySelector('#connection').textContent = navigator.onLine ? '' : t('Offline','Offline');
}
function render(focus = false) {
  languageUI();
  if(view === 'home') home(); else if(session.index === 10) results(); else quiz();
  if(focus) { main.focus(); window.scrollTo({top:0,behavior:'instant'}); }
}
function home() {
  const completed = new Set(history.map(h => h.title).filter(x => typeof x === 'number'));
  main.innerHTML = `<section class="hero"><div class="hero-copy"><div class="eyebrow hero-label"><span></span>${t('DIN VÄG TILL NY KUNSKAP','YOUR PATH TO NEW KNOWLEDGE')}</div><h1>${t('Lär känna Sverige.<br><em>En fråga i taget.</em>','Get to know Sweden.<br><em>One question at a time.</em>')}</h1><p>${t('Öva inför medborgarskapsprovet i din egen takt. Växla mellan svenska och engelska, förstå svaren och lär dig något nytt varje gång.','Practise for the Swedish citizenship test at your own pace. Switch between Swedish and English, understand the answers, and learn something new every time.')}</p><button class="primary" data-action="random">${t('Starta ett blandat quiz','Start a mixed quiz')} <span>↗</span></button><span class="hero-meta">${t('10 frågor · Ingen tidspress · Helt gratis','10 questions · No time limit · Completely free')}</span></div><div class="hero-art" aria-hidden="true"><div class="art-sun"></div><div class="art-caption">SVERIGE<br><span>59° N 18° E</span></div><svg viewBox="0 0 420 260"><path fill="#c5d8ce" d="M0 160Q60 100 145 155T300 135T420 150V260H0Z"/><path fill="#719d8b" d="M0 197Q80 158 162 185T340 172T420 179V260H0Z"/><g fill="#305e51"><path d="M22 195h55V118H22zM17 118l33-32 32 32zM47 88V64h6v24z"/><path d="M100 199v-89h17V72h6v38h17v89zM112 72l8-25 8 25z"/><path d="M158 203v-71h55v71zM155 132l30-31 31 31zM223 204v-51h45v51zM280 206v-91h56v91zM276 115l33-24 32 24zM345 210v-57h54v57z"/></g><g fill="#efda96"><path d="M36 139h10v18H36zM56 139h10v18H56zM112 133h15v20h-15zM172 149h9v15h-9zM192 149h9v15h-9zM292 134h11v17h-11zM314 134h11v17h-11zM358 169h10v15h-10zM378 169h10v15h-10z"/></g><path fill="#173f38" d="M0 222q80-23 145-5t145-2 130-3v48H0z"/><path d="M12 244h85m65-7h69m71 8h86" stroke="#6e9380" stroke-width="2"/></svg><div class="art-note">${t('Nyfikenhet tar dig vidare.','Curiosity takes you further.')}</div></div></section>
  <section class="facts" aria-label="${t('Om övningarna','About the exercises')}"><div><strong>100</strong><span>${t('källbaserade frågor','source-based questions')}</span></div><div><strong>10</strong><span>${t('frågor per quiz','questions per quiz')}</span></div><div><strong>SV <span class="arrow">⇄</span> EN</strong><span>${t('byt språk när du vill','switch language anytime')}</span></div><div><strong>${t('Direkt','Instant')}</strong><span>${t('svar med förklaring','feedback with context')}</span></div></section>
  ${session && session.index < 10 ? `<div class="resume"><div><strong>${t('Fortsätt där du slutade','Pick up where you left off')}</strong><p>${Object.keys(session.answers).length} / 10 ${t('frågor besvarade','questions answered')}</p></div><button class="primary" data-action="resume">${t('Fortsätt quiz','Resume quiz')} →</button></div>` : ''}
  <section class="quiz-library"><div class="section-title"><div><span class="eyebrow">${t('SMÅ STEG. STORA INSIKTER.','SMALL STEPS. BIG DISCOVERIES.')}</span><h2>${t('Välj ditt nästa quiz','Choose your next quiz')}</h2></div><span class="pill">${completed.size} / 10 ${t('genomförda','completed')}</span></div><p class="section-description">${t('Tio övningspass som tillsammans täcker alla 100 frågor. Eller blanda frågor för en ny utmaning.','Ten practice sets covering all 100 questions. Or mix the questions for a fresh challenge.')}</p><div class="quiz-grid">${Array.from({length:10},(_,i) => { const qs = questions.slice(i*10,i*10+10), categories = [...new Set(qs.map(q => q.category[lang]))]; const best = history.filter(h => h.title===i).reduce((m,h)=>Math.max(m,h.score),-1); return `<button class="quiz-card" data-set="${i}"><div class="card-top"><span class="set-number">${String(i+1).padStart(2,'0')}</span><span class="card-arrow">↗</span></div><h3>${esc(categories.slice(0,2).join(' & '))}</h3><p>${t('Övningspass','Practice set')} ${i+1} <span>·</span> 10 ${t('frågor','questions')}</p><div class="card-bottom">${best >= 0 ? `<span class="done">✓ ${t('Bästa resultat','Best score')}: ${best}/10</span>` : `<span>${t('Redo när du är','Ready when you are')}</span>`}<span>→</span></div></button>`; }).join('')}</div></section>
  <section class="book-note"><div class="book-symbol" aria-hidden="true">▤</div><div><span class="eyebrow">${t('KUNSKAP MED EN KÄLLA','KNOWLEDGE WITH A SOURCE')}</span><h2>${t('Läs. Öva. Förstå.','Read. Practise. Understand.')}</h2><p>${t('Alla frågor bygger på Sverige i fokus från UHR och Skolverket, korrigerad upplaga 10 augusti 2026. Efter varje svar får du ett originalutdrag, en engelsk översättning och rätt sida att läsa vidare på.','Every question is based on Sverige i fokus from UHR and Skolverket, corrected edition 10 August 2026. After each answer, see an original excerpt, an English translation and the page to read next.')}</p><a href="./documents/sverige-i-fokus.pdf" target="_blank" rel="noopener">${t('Öppna utbildningsmaterialet','Open the source material')} ↗ <small>PDF · 11 MB</small></a></div></section><p class="disclaimer">${t('Detta är egna övningsfrågor, inte officiella provfrågor. Resultatet är ett övningsresultat och anger inte om du blir godkänd på det riktiga provet. Översättningarna är stöd för lärandet. Svenska originaltexten är källan.','These are original practice questions, not official test questions. Your practice score does not determine whether you will pass the real test. Translations are learning aids; the original Swedish text is the source.')} ${t('Frågor och utdrag kan användas offline efter första besöket. PDF-boken kräver internet tills du väljer att spara den offline.','Questions and excerpts work offline after your first visit. The PDF needs internet until you choose to save it offline.')}</p><button class="secondary" data-action="cache-pdf">${t('Spara PDF för offlinebruk (11 MB)','Save PDF for offline use (11 MB)')}</button><p id="cache-status" role="status"></p>${!storageOK ? `<p role="status">${t('Webbläsaren tillåter inte sparad historik. Du kan fortfarande öva.','Your browser cannot save progress. You can still practise.')}</p>` : ''}`;
}
function quiz() {
  const q = questions.find(q => q.id === session.ids[session.index]), answer = session.answers[q.id], answered = answer !== undefined, correct = answer === q.correct;
  main.innerHTML = `<div class="quiz-shell"><div class="quiz-toolbar"><button class="text-button" data-action="home">← ${t('Alla quiz','All quizzes')}</button><span>${t('Övningspass','Practice set')} ${typeof session.title === 'number' ? session.title+1 : t('· Blandat','· Mixed')}</span></div><div class="progress-label"><span>${t('Fråga','Question')} ${session.index+1} <span class="muted">/ 10</span></span><span>${score(session,questions)} ${t('rätt','correct')}</span></div><div class="progress" role="progressbar" aria-label="${t('Besvarade frågor','Answered questions')}" aria-valuenow="${Object.keys(session.answers).length}" aria-valuemin="0" aria-valuemax="10"><div style="width:${Object.keys(session.answers).length*10}%"></div></div><section class="question-card"><div class="question-meta"><span class="eyebrow">${esc(q.category[lang])}</span><div class="language" aria-label="${t('Frågans språk','Question language')}"><button data-lang="sv" aria-pressed="${lang==='sv'}" class="${lang==='sv'?'active':''}">Svenska</button><button data-lang="en" aria-pressed="${lang==='en'}" class="${lang==='en'?'active':''}">English</button></div></div><h1>${esc(q.question[lang])}</h1>${validationStatus(q)}<p class="muted">${t('Välj ett svar. Du får återkoppling direkt.','Choose an answer for immediate feedback.')}</p><div class="answers">${session.orders[q.id].map((id,i) => { const o=q.options.find(o=>o.id===id); return `<button class="answer ${answered && id===q.correct?'correct':''} ${answered && id===answer && !correct?'incorrect':''}" data-answer="${id}" ${answered?'disabled':''}><span class="answer-letter">${String.fromCharCode(65+i)}</span><span>${esc(o[lang])}</span>${answered && id===q.correct?`<span class="answer-mark">✓ <span class="sr-only">${t('Rätt svar','Correct answer')}</span></span>`:answered&&id===answer?`<span class="answer-mark">× <span class="sr-only">${t('Ditt svar','Your answer')}</span></span>`:''}</button>`; }).join('')}</div></section>${answered?`<section class="feedback ${correct?'positive':'negative'}"><div role="status"><h2>${correct?t('✓ Rätt svar!','✓ Correct!'):t('Inte riktigt — nu lär vi oss.','Not quite — let’s learn from it.')}</h2><p>${t('Rätt svar','Correct answer')}: <strong>${esc(q.options.find(o=>o.id===q.correct)[lang])}</strong></p></div>${excerpts(q)}</section><div class="next-row"><span>${t('Varje fråga är ett steg framåt.','Every question is a step forward.')}</span><button class="primary" data-action="next">${session.index===9?t('Se mitt resultat','See my results'):t('Nästa fråga','Next question')} →</button></div>`:`<p class="quiz-hint">${t('Du kan byta språk utan att lämna frågan.','You can switch languages without leaving the question.')}</p>`}</div>`;
}
function results() {
  const total=score(session,questions);
  if(!session.saved) { history.push({title:session.title,score:total,date:new Date().toISOString()}); history=history.slice(-100); session.saved=true; save(); }
  const missed=session.ids.filter(id=>session.answers[id]!==questions.find(q=>q.id===id).correct);
  main.innerHTML=`<div class="quiz-shell"><button class="text-button" data-action="home">← ${t('Alla quiz','All quizzes')}</button><section class="result-hero"><span class="eyebrow">${t('ÖVNINGSPASSET ÄR KLART','PRACTICE COMPLETE')}</span><div class="score-circle"><strong>${total}<small>/10</small></strong><span>${total*10}%</span></div><h1>${total===10?t('Alla rätt. Bra jobbat!','A perfect score. Well done!'):total>=7?t('Du är på god väg!','You’re making good progress!'):t('Varje övning gör skillnad.','Every practice makes a difference.')}</h1><p>${t(`Du svarade rätt på ${total} av 10 frågor. Läs igenom svaren nedan och fortsätt bygga din kunskap.`,`You answered ${total} of 10 questions correctly. Review your answers below and keep building your knowledge.`)}</p><div class="result-actions"><button class="primary" data-action="random">${t('Nytt blandat quiz','New mixed quiz')} ↗</button><button class="secondary" data-action="retry">${t('Gör om detta quiz','Retry this quiz')}</button></div></section><div class="section-title"><h2>${t('Dina svar & lästips','Your answers & reading tips')}</h2><span>${missed.length} ${t('att repetera','to revisit')}</span></div>${session.ids.map((id,i)=>{const q=questions.find(q=>q.id===id),right=session.answers[id]===q.correct;return `<details class="review"><summary><span class="review-icon ${right?'right':'wrong'}">${right?'✓':'×'}</span><span>${i+1}. ${esc(q.question[lang])}</span><span class="review-page">${t('s.','p.')} ${q.page}</span></summary><div class="review-body">${validationStatus(q)}<p>${t('Ditt svar','Your answer')}: <strong>${esc(q.options.find(o=>o.id===session.answers[id])[lang])}</strong></p>${!right?`<p>${t('Rätt svar','Correct answer')}: <strong>${esc(q.options.find(o=>o.id===q.correct)[lang])}</strong></p>`:''}${excerpts(q)}</div></details>`;}).join('')}<p class="disclaimer">${t('Detta är ett övningsresultat, inte ett officiellt besked om godkänt prov.','This is a practice score, not an official pass or fail result.')}</p></div>`;
}
document.addEventListener('click', async event => {
 const b=event.target.closest('button'); if(!b)return;
 if(b.dataset.lang) {lang=b.dataset.lang;save();render();return;}
 if(b.dataset.set!==undefined) {const n=Number(b.dataset.set);session=createSession(questions.slice(n*10,n*10+10),n);view='quiz';save();render(true);return;}
 if(b.dataset.answer!==undefined && session) { const id=session.ids[session.index]; if(session.answers[id]!==undefined)return;session.answers[id]=b.dataset.answer;save();render();document.querySelector('[data-action="next"]').focus();return; }
 switch(b.dataset.action) {
 case 'random': session=createSession(questions,'mixed');view='quiz';save();render(true);break;
 case 'home': view='home';render(true);break;
 case 'resume': view='quiz';render(true);break;
 case 'retry': session=createSession(session.ids.map(id=>questions.find(q=>q.id===id)),session.title);save();render(true);break;
 case 'next': if(session.answers[session.ids[session.index]]===undefined)return;session.index++;save();render(true);break;
 case 'cache-pdf': {const status=document.querySelector('#cache-status');b.disabled=true;status.textContent=t('Sparar PDF…','Saving PDF…');try{if(!('caches' in window))throw new Error(); const cache=await caches.open('medborgarskapsprov-documents-v1');await cache.add('./documents/sverige-i-fokus.pdf');status.textContent=t('PDF-boken är sparad för offlinebruk.','The PDF is saved for offline use.');}catch{status.textContent=t('Kunde inte spara PDF. Kontrollera anslutningen och försök igen.','Could not save the PDF. Check your connection and try again.');}finally{b.disabled=false;}break;}
 }
});
window.addEventListener('beforeinstallprompt', e=>{e.preventDefault();deferredInstall=e;document.querySelector('#install').hidden=false;});
document.querySelector('#install').onclick=async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;document.querySelector('#install').hidden=true;}};
window.addEventListener('appinstalled',()=>{document.querySelector('#install').hidden=true;});
window.addEventListener('online',languageUI);window.addEventListener('offline',languageUI);
try {
 const response=await fetch('./data/questions.json');if(!response.ok)throw new Error('Questions unavailable');questions=await response.json();
 try {const stored=JSON.parse(localStorage.getItem(KEY));if(stored){lang=stored.lang==='en'?'en':'sv';session=validSession(stored.session,questions)?stored.session:null;history=Array.isArray(stored.history)?stored.history.filter(h=>h&&Number.isInteger(h.score)&&h.score>=0&&h.score<=10&&(h.title==='mixed'||Number.isInteger(h.title)&&h.title>=0&&h.title<10)).slice(-100):[];}}catch{storageOK=false;}
 render();
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{document.querySelector('#connection').textContent=t('Offline ej tillgängligt','Offline unavailable');});
}catch{main.innerHTML='<section class="result-hero"><h1>Kunde inte ladda frågorna / Could not load questions</h1><p>Kontrollera anslutningen och ladda om sidan. / Check your connection and reload.</p><a href="./">Försök igen / Try again</a></section>';}
