import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createSession,score,validSession,shuffle} from '../quiz.js';
const qs=JSON.parse(await readFile(new URL('../data/questions.json',import.meta.url),'utf8'));
test('100 unique, fully bilingual, source-cited questions across 13 chapters',()=>{assert.equal(qs.length,100);assert.equal(new Set(qs.map(q=>q.id)).size,100);assert.equal(new Set(qs.map(q=>q.question.sv)).size,100);assert.equal(new Set(qs.map(q=>q.category.sv)).size,13);for(const q of qs){assert.ok(q.page>=5&&q.page<=47);for(const l of ['sv','en']){assert.ok(q.question[l].length>10);assert.ok(q.excerpt[l].length>10);assert.equal(new Set(q.options.map(o=>o[l])).size,3);}assert.ok(q.options.some(o=>o.id===q.correct));}});
test('ten practice sets cover every question exactly once',()=>{const ids=[];for(let i=0;i<10;i++){const s=createSession(qs.slice(i*10,i*10+10),i);assert.equal(s.ids.length,10);assert.ok(validSession(s,qs));ids.push(...s.ids);}assert.equal(new Set(ids).size,100);});
test('mixed sessions have 10 unique questions and stable shuffled option ids',()=>{for(let i=0;i<100;i++){const s=createSession(qs,'mixed');assert.equal(new Set(s.ids).size,10);assert.ok(validSession(s,qs));for(const id of s.ids)assert.deepEqual([...s.orders[id]].sort(),['0','1','2']);}});
test('scores use answer identity, not shuffled position',()=>{const s=createSession(qs,0);s.ids.forEach((id,i)=>s.answers[id]=i<7?'0':'1');s.index=10;assert.equal(score(s,qs),7);assert.ok(validSession(s,qs));});
test('corrupt or outdated persisted sessions are rejected',()=>{const s=createSession(qs,0);assert.equal(validSession({...s,index:10},qs),false);assert.equal(validSession({...s,ids:Array(10).fill('q001')},qs),false);assert.equal(validSession({...s,orders:{}},qs),false);assert.equal(validSession(null,qs),false);assert.equal(validSession({...s,index:-1},qs),false);});
test('shuffle preserves input and supports deterministic verification',()=>{const input=[1,2,3];assert.deepEqual(shuffle(input,()=>0),[2,3,1]);assert.deepEqual(input,[1,2,3]);});
